name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd vue-poker
          npm install

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          # Optional version of wasm-pack to install(eg. 'v0.9.1', 'latest')
          version: 'latest'

      - name: Setup Cargo 
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run Rust tests  
        run: |
          cd rust
          cargo test

      - name: Build Rust Wasm
        run: |
          cd vue-poker
          npm run r1-build-release
          npm run r2-build-release

      - name: Build Vue.js app
        run: |
          cd vue-poker
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: vue-poker/dist # The folder the action should deploy