name: Build and Deploy

on:
  push:
    branches:
      - main
      - eval3

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd vue-poker
          npm install

      - name: Build Vue.js app
        run: |
          cd vue-poker
          npm run build2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Rust Wasm
        run: |
          cd rust
          wasm-pack build --dev --target web --out-dir ../../vue-poker/pkg poker_eval
